---
app_dev:
  hosts:
    t5g5.d.mapelabs.eu:

app_prod:
  hosts:
    t5g5-prod.d.mapelabs.eu:

app:
  children:
    app_dev:
    app_prod:

all:
  vars:
    ansible_user: ans
    ansible_become: yes
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_method: sudo
